partition: "aics_gpu_general"
worker_time_limit: "9-24:00:00"
gpus:
    gtx1080:
        cluster_size: 4
        memory_limit: "60G"        
    titanx:
        cluster_size: 8
        memory_limit: "60G"
    titanxp:
        cluster_size: 4
        memory_limit: "60G"
    v100:
        cluster_size: 12
        memory_limit: "120G"
